export const GET_INDEX_IMG = 'GET_INDEX_IMG'
export const GET_INDEX_IMG_REQUEST = 'GET_INDEX_IMG_REQUEST'
export const GET_INDEX_IMG_SUCCESS = 'GET_INDEX_IMG_SUCCESS'
export const GET_INDEX_IMG_FAILURE = 'GET_INDEX_IMG_FAILURE'


export const GET_APPS = 'GET_APPS'
export const GET_APPS_SUCCESS = 'GET_APPS_SUCCESS'
export const GET_APPS_FAILURE = 'GET_APPS_FAILURE'
export const GET_APPS_REQUEST = 'GET_APPS_REQUEST'

export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'